node {



stage('Check-out') {
echo 'From check-out stage'
}



stage('Bazel Build') {
echo 'From Bazel Build stage'
 sh '''
	pwd
	ls
	cd bazel/examples/cpp
	bazel build //main:hello-world
	'''
}



}
